const holder1 = document.querySelector('#holder1');
const holder2 = document.querySelector('#holder2');
const holder3 = document.querySelector('#holder3');
const hiThere = document.querySelector('#hi');
const trackingBtn = document.querySelector('#trackingBtn');
const historyBtn = document.querySelector('#historyBtn');
const historyView = document.querySelector('#historyView');
const nextBtn = document.querySelector('#nextBtn');
const nextBtn2 = document.querySelector('#nextBtn2');
const resetBtn = document.querySelector('#reset');
const nameInput = document.querySelector('#nameUser');
const packInput = document.querySelector('#pack');
const allList1 = document.querySelectorAll('.pre');
const container2 = document.querySelector('#container2');
const cigarettesCard = document.querySelector('#cigarettes');
const smokeCard = document.querySelector('#smoke');
const moneyCard = document.querySelector('#money');
const cigaretteRecordsView = document.querySelector('#holdImg');
const cigConsumtion = document.querySelector('#cigConsumtion');
const moneyConsumtion = document.querySelector('#moneyConsumtion');
let goingSmoke = document.querySelector('#going');
let manuallySmoke = document.querySelector('#manually');
let averageSmoke = document.querySelector('#average');
let numAverage = document.querySelector('#numAverage');
let smokeCig = document.querySelector('#smokeCig');
let vincentGif = document.querySelector('#vincent');
let miaGif = document.querySelector('#mia');
const backBtn = document.querySelector('#back');
const backToStartBtn = document.querySelector('#backToStart');
let manuallyInput = document.querySelector('#manuallyInput');
let dayC = document.querySelector('#dayC');
let dayM = document.querySelector('#dayM');
let weekC = document.querySelector('#weekC');
let weekM = document.querySelector('#weekM');
let monthC = document.querySelector('#monthC');
let monthM = document.querySelector('#monthM');
let yearC = document.querySelector('#yearC');
let yearM = document.querySelector('#yearM');
let cigarIncrement = document.querySelector('#sp');
let clock = document.querySelector('#clock');
let time = new Date();
let averageForDay;
let averageToDay;
let gf1;
let gf2;
let dan = document.querySelector('#d');
let mesec = document.querySelector('#mt');
let godina = document.querySelector('#y');
let datum = document.querySelector('#date');
let sati = document.querySelector('#h');
let minuti = document.querySelector('#m');
let sekunde = document.querySelector('#s');
let min = document.querySelector('#min');
let sat = document.querySelector('#sat');
let dani = document.querySelector('#dan');
let startSat;
let startMin;
let sat1;
let min1;
let sec1;
let br = 0;
let historyObj = {cigar: []};
let historyDates = {date: []};
